#ifndef RESEND_PROTOCOL_DEFINE_H
#define RESEND_PROTOCOL_DEFINE_H

#define MP_MAGIC_HEAD "wisdom.cf.mp"
#define MP_MAGIC_HEAD_LEN 12
#define MP_STREAM_TAG_LEN 1

#endif // RESEND_PROTOCOL_DEFINE_H
